'use strict';
const $=id=>document.getElementById(id);const C={cyan:'#13adb2',coral:'#ed7965',ink:'#254653'};
let game=null,playing=false,paused=false,difficulty='easy',selection=[],mode=null,hover=null,drag=null,ended=false,last=0,step=0,soundEnabled=false,audioCtx=null,toastTimer=0,menuTime=0;const canvas=$('map'),ctx=canvas.getContext('2d'),bg=$('backdrop'),bctx=bg.getContext('2d');let view={x:0,y:0,cell:10,w:0,h:0};
const buildings={relay:{name:'Relais',desc:'Étendre votre couleur',icon:'◈',key:'R',cost:40},extractor:{name:'Extracteur',desc:'Exploiter une source',icon:'◉',key:'E',cost:65},bastion:{name:'Bastion',desc:'Protéger une frontière',icon:'⬡',key:'B',cost:85}};
const units={scout:{name:'Éclaireur',desc:'Explorer rapidement',icon:'●',key:'1',cost:25},fighter:{name:'Combattant',desc:'Conquérir et défendre',icon:'■',key:'2',cost:40},breaker:{name:'Briseur',desc:'Attaquer les bâtiments',icon:'▲',key:'3',cost:70}};
function cost(type){const e=window.CQEngine;return e?.COSTS?.[type]??e?.COSTS?.buildings?.[type]??e?.COSTS?.units?.[type]??e?.BUILDING_STATS?.[type]?.cost??e?.UNIT_STATS?.[type]?.cost??buildings[type]?.cost??units[type]?.cost??0}
function audio(name='click_001'){if(!soundEnabled)return;const a=new Audio('assets/audio/'+name+'.ogg');a.volume=.25;a.play().catch(()=>{try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.connect(g);g.connect(audioCtx.destination);o.frequency.value=name.includes('error')?180:640;g.gain.setValueAtTime(.035,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.12);o.start();o.stop(audioCtx.currentTime+.13)}catch{}});}
function toggleSound(){soundEnabled=!soundEnabled;for(const el of [$('sound'),$('menuSound')]){el.setAttribute('aria-label',soundEnabled?'Couper le son':'Activer le son');el.style.color=soundEnabled?C.cyan:'';} $('menuSound').innerHTML='♫ <span>Son '+(soundEnabled?'activé':'désactivé')+'</span>';audio('glass_001')}
$('sound').onclick=$('menuSound').onclick=toggleSound;
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3300)}
function commandHTML(type,v,kind){return `<button class="command" data-${kind}="${type}" title="${v.desc} (${v.key})"><span class="symbol">${v.icon}</span><span class="description"><strong>${v.name}</strong><small>${v.desc}</small></span><span class="cost"><b>${cost(type)}</b> <i>◉</i><kbd>${v.key}</kbd></span></button>`}
function createCommands(){$('buildButtons').innerHTML=Object.entries(buildings).map(([k,v])=>commandHTML(k,v,'build')).join('');$('unitButtons').innerHTML=Object.entries(units).map(([k,v])=>commandHTML(k,v,'recruit')).join('');document.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>setMode({kind:'build',type:b.dataset.build}));document.querySelectorAll('[data-recruit]').forEach(b=>b.onclick=()=>recruit(b.dataset.recruit));}
function recruit(type){if(!game||paused||ended)return;const result=game.recruit(1,type);if(result?.ok===false){toast(result.message||'Pas assez de pigment.');audio('error_001')}else{toast((units[type]?.name||'Unité')+' en formation près du Cœur');audio('confirmation_001')}}
function setMode(m){if(!game||ended)return;if(paused)togglePause();mode=m;document.querySelectorAll('.command.active,.powers .active,.orders .active').forEach(e=>e.classList.remove('active'));$('placementHint').classList.toggle('hidden',!m);if(m){const labels={build:'Touchez votre territoire pour placer : '+(buildings[m.type]?.name||''),move:'Touchez la destination de vos unités',power:'Touchez la zone à influencer'};$('placementHint').textContent=labels[m.kind]+' · Annuler ✕';if(m.kind==='build')document.querySelector(`[data-build="${m.type}"]`)?.classList.add('active');if(m.kind==='power')document.querySelector(`[data-power="${m.type}"]`)?.classList.add('active');audio()}}
$('placementHint').style.pointerEvents='auto';$('placementHint').onclick=()=>setMode(null);
function start(){if(!window.CQEngine){toast('Le moteur de jeu est indisponible.');return;}game=new CQEngine.Game({difficulty,seed:Math.floor(Math.random()*1000000)});selection=[];mode=null;playing=true;paused=false;ended=false;step=0;$('menu').classList.add('hidden');$('game').classList.remove('hidden');closeModal();$('pauseFlag').classList.add('hidden');$('pause').textContent='Ⅱ';createCommands();setStep();resize();audio('jingles_PIZZI00');toast('Votre couleur commence ici. Construisez un relais !')}
$('play').onclick=start;document.querySelectorAll('[data-difficulty]').forEach(b=>b.onclick=()=>{difficulty=b.dataset.difficulty;document.querySelectorAll('[data-difficulty]').forEach(e=>e.classList.toggle('chosen',e===b));audio()});
function togglePause(){if(!playing||ended)return;paused=!paused;$('pauseFlag').classList.toggle('hidden',!paused);$('pause').textContent=paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',paused?'Reprendre':'Mettre en pause')}
$('pause').onclick=togglePause;
function modal(html){$('modalContent').innerHTML=html;$('modal').classList.remove('hidden');$('closeModal').focus()}
function closeModal(){$('modal').classList.add('hidden')}$('closeModal').onclick=closeModal;
function help(){if(playing&&!paused)togglePause();modal(`<div class="eyebrow">COMMENT JOUER</div><h2>Votre couleur fait son chemin.</h2><p>Contrôlez <b>60 % du terrain pendant 45 secondes</b>. Seul le territoire relié à votre Cœur compte. Au bout de 12 minutes, le camp qui possède le plus de terrain connecté l’emporte. Détruire le Cœur adverse donne aussi la victoire.</p><ul><li><b>Développer :</b> placez des relais sur votre couleur pour agrandir le réseau. Un extracteur doit être posé sur une source dorée.</li><li><b>Mobiliser :</b> recrutez des unités avec votre pigment. Touchez une unité pour la sélectionner, puis le terrain pour lui donner une destination.</li><li><b>Conquérir :</b> vos combattants prennent le terrain autour d’eux. Coupez les connexions adverses pour isoler leur réseau.</li><li><b>Sur ordinateur :</b> sélection par clic ou glisser ; clic droit pour se déplacer. <kbd>A</kbd> toute l’armée · <kbd>R</kbd> relais · <kbd>E</kbd> extracteur · <kbd>B</kbd> bastion · <kbd>1</kbd><kbd>2</kbd><kbd>3</kbd> recruter · <kbd>Espace</kbd> pause.</li></ul><button class="primary" id="helpDone">C’est parti →</button><button class="secondary" id="helpSound">♫ Activer / couper le son</button>`);$('helpSound').onclick=toggleSound;$('helpDone').onclick=()=>{closeModal();if(playing&&paused)togglePause()}}
$('howto').onclick=$('helpGame').onclick=$('mobileHelp').onclick=help;
$('credits').onclick=()=>modal(`<div class="eyebrow">COLORQUEST · PREMIÈRE ÉDITION</div><h2>Une toile à partager.</h2><p>Un jeu de stratégie minimaliste conçu pour Martinus Games. Carte, unités et animations dessinées en temps réel, sans dépendance graphique externe.</p><p>Effets sonores et courts jingles : <a href="https://kenney.nl/assets" target="_blank" rel="noopener">Kenney</a>, licence CC0. Le son est désactivé au démarrage ; activez-le avec ♫.</p><p>Prototype jouable : le rythme et l’équilibrage évolueront avec vos retours.</p>`);
$('back').onclick=()=>{if(!paused)togglePause();modal(`<div class="eyebrow">UNE PAUSE DANS LA CONQUÊTE</div><h2>Votre réseau vous attend.</h2><p>Quitter la partie fera perdre votre progression actuelle.</p><button id="resume" class="primary">Reprendre la partie →</button><button id="exit" class="secondary">Quitter et retourner au menu</button>`);$('resume').onclick=()=>{closeModal();if(paused)togglePause()};$('exit').onclick=()=>{playing=false;closeModal();$('game').classList.add('hidden');$('menu').classList.remove('hidden');resize()}};
function selectAll(){if(!game)return;selection=game.units.filter(u=>u.team===1&&u.hp>0).map(u=>u.id);mode=null;setMode(null);toast(selection.length+' unités sélectionnées · touchez une destination');audio('select_001')}$('selectAll').onclick=selectAll;$('moveOrder').onclick=()=>{if(!selection.length)selectAll();setMode({kind:'move'})};document.querySelectorAll('[data-power]').forEach(b=>b.onclick=()=>setMode({kind:'power',type:b.dataset.power}));
const steps=[['Faites grandir votre couleur','Placez un relais sur votre territoire, vers une source dorée.'],['Alimentez votre expansion','Posez un extracteur sur une source dorée reliée à votre Cœur.'],['Formez votre première armée','Recrutez des combattants. Sélectionnez-les, puis touchez leur destination.']];function setStep(){$('stepNumber').textContent='0'+(step+1)+' / 03';$('stepTitle').textContent=steps[step][0];$('stepText').textContent=steps[step][1]}$('nextStep').onclick=()=>{step=(step+1)%3;setStep()};
function resize(){for(const c of [canvas,bg]){const r=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);c.width=Math.max(1,Math.round(r.width*dpr));c.height=Math.max(1,Math.round(r.height*dpr));c.getContext('2d').setTransform(dpr,0,0,dpr,0,0)}const w=canvas.clientWidth,h=canvas.clientHeight,W=window.CQEngine?.WIDTH||32,H=window.CQEngine?.HEIGHT||44;view={w,h,cell:Math.min((w-14)/W,(h-14)/H),x:0,y:0};view.x=(w-W*view.cell)/2;view.y=(h-H*view.cell)/2}
addEventListener('resize',resize);new ResizeObserver(resize).observe($('canvasWrap'));
function screenPos(e){const r=canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top}}
function gridPos(p){return{x:(p.x-view.x)/view.cell,y:(p.y-view.y)/view.cell}}
function tileAt(x,y){const W=CQEngine.WIDTH,H=CQEngine.HEIGHT;if(x<0||y<0||x>=W||y>=H)return null;return game.tiles[Math.floor(y)*W+Math.floor(x)]}
canvas.addEventListener('pointerdown',e=>{if(!playing||paused||ended)return;canvas.setPointerCapture(e.pointerId);const p=screenPos(e);drag={start:p,last:p,id:e.pointerId,button:e.button,touch:e.pointerType==='touch'};hover=gridPos(p)});
canvas.addEventListener('pointermove',e=>{hover=gridPos(screenPos(e));if(drag)drag.last=screenPos(e)});
canvas.addEventListener('pointerleave',()=>{hover=null});canvas.addEventListener('contextmenu',e=>e.preventDefault());
canvas.addEventListener('pointerup',e=>{if(!drag||paused||ended){drag=null;return}const d=drag;drag=null;const p=gridPos(screenPos(e));const t=tileAt(p.x,p.y);if(!t)return;const distance=Math.hypot(d.last.x-d.start.x,d.last.y-d.start.y);if(mode?.kind==='build'){let bx=Math.floor(p.x),by=Math.floor(p.y);if(mode.type==='extractor'){const near=game.tiles.filter(t=>t.source&&t.explored&&t.owner===1&&t.connected).map(t=>({t,d:Math.hypot(t.x+.5-p.x,t.y+.5-p.y)})).sort((a,b)=>a.d-b.d)[0];if(near&&near.d<Math.max(2,24/view.cell)){bx=near.t.x;by=near.t.y}}const result=game.build(1,mode.type,bx,by);if(result?.ok===false){toast(result.message||'Impossible de construire ici.');audio('error_001')}else{audio('drop_001');toast('Construction lancée : '+buildings[mode.type].name);setMode(null)}return}if(mode?.kind==='power'){const r=game.power(1,mode.type,Math.floor(p.x),Math.floor(p.y));toast(r?.message||(r?.ok===false?'Pouvoir indisponible.':'Pouvoir activé'));audio(r?.ok===false?'error_001':'glass_001');if(r?.ok!==false)setMode(null);return}if(distance>9&&!d.touch&&d.button===0){const a=gridPos(d.start),b=gridPos(d.last);selection=game.units.filter(u=>u.team===1&&u.hp>0&&u.x>=Math.min(a.x,b.x)&&u.x<=Math.max(a.x,b.x)&&u.y>=Math.min(a.y,b.y)&&u.y<=Math.max(a.y,b.y)).map(u=>u.id);audio('select_001');return}const nearest=game.units.filter(u=>u.team===1&&u.hp>0).map(u=>({u,d:Math.hypot(u.x-p.x,u.y-p.y)})).sort((a,b)=>a.d-b.d)[0];if(d.button!==2&&mode?.kind!=='move'&&nearest?.d<Math.max(1.25,20/view.cell)){selection=e.shiftKey?[...new Set([...selection,nearest.u.id])]:[nearest.u.id];audio('select_001');return}if(selection.length){const result=game.order(selection,p.x,p.y);if(result?.ok===false){toast(result.message||'Destination inaccessible.');audio('error_001');return}audio('click_001');moveMarker={x:p.x,y:p.y,life:1};setMode(null)}else toast('Sélectionnez une unité ou utilisez « Toute l’armée ».')});
canvas.addEventListener('pointercancel',()=>{drag=null});let moveMarker=null;
addEventListener('keydown',e=>{if(!playing||!$('modal').classList.contains('hidden'))return;const key=e.key.toLowerCase();if([' ','escape','a','r','e','b','1','2','3'].includes(key))e.preventDefault();if(key===' '){togglePause();return}if(key==='escape'){setMode(null);selection=[];return}if(paused)return;if(key==='a')selectAll();if(key==='r')setMode({kind:'build',type:'relay'});if(key==='e')setMode({kind:'build',type:'extractor'});if(key==='b')setMode({kind:'build',type:'bastion'});if(key==='1')recruit('scout');if(key==='2')recruit('fighter');if(key==='3')recruit('breaker')});
function color(team){return team===1?C.cyan:C.coral}function roundRect(c,x,y,w,h,r){c.beginPath();c.roundRect(x,y,w,h,r)}
function drawBuilding(c,b,s,time,ghost=false){const x=view.x+(b.x+.5)*s,y=view.y+(b.y+.5)*s,r=s*(b.type==='core'?1.02:.66),col=color(b.team);c.save();c.translate(x,y);c.globalAlpha=ghost?.5:1;if(b.type==='core'){c.strokeStyle=col+'40';c.lineWidth=1;c.beginPath();c.arc(0,0,r*(1.5+Math.sin(time*1.5)*.08),0,Math.PI*2);c.stroke()}c.shadowColor='#28495724';c.shadowBlur=5;c.shadowOffsetY=2;c.fillStyle='#fffef9';c.strokeStyle=col;c.lineWidth=Math.max(1.4,s*.14);c.beginPath();if(b.type==='core'||b.type==='bastion'){for(let i=0;i<6;i++){const a=i*Math.PI/3-Math.PI/2;c.lineTo(Math.cos(a)*r,Math.sin(a)*r)}}else if(b.type==='relay'){c.moveTo(0,-r);c.lineTo(r,0);c.lineTo(0,r);c.lineTo(-r,0)}else c.arc(0,0,r,0,Math.PI*2);c.closePath();c.fill();c.stroke();c.shadowBlur=0;c.shadowOffsetY=0;c.fillStyle=col;if(b.type==='core'){roundRect(c,-r*.4,-r*.4,r*.8,r*.8,r*.15);c.fill()}else if(b.type==='extractor'){c.beginPath();c.arc(0,0,r*.45,0,Math.PI*2);c.fill();c.strokeStyle='#fff';c.lineWidth=1;c.beginPath();c.moveTo(-r*.3,0);c.lineTo(r*.3,0);c.stroke()}else if(b.type==='bastion'){c.beginPath();c.moveTo(0,-r*.5);c.lineTo(r*.42,r*.35);c.lineTo(-r*.42,r*.35);c.fill()}else{c.beginPath();c.arc(0,0,r*.25,0,Math.PI*2);c.fill()}c.restore();if(b.hp<b.maxHp&&!ghost)healthbar(x,y+r+3,r*2,b.hp/b.maxHp,col)}
function healthbar(x,y,w,p,col){ctx.fillStyle='#ffffffb0';ctx.fillRect(x-w/2,y,w,2);ctx.fillStyle=col;ctx.fillRect(x-w/2,y,w*Math.max(0,p),2)}
function drawMap(dt,time){const c=ctx,s=view.cell,W=CQEngine.WIDTH,H=CQEngine.HEIGHT;c.clearRect(0,0,view.w,view.h);c.fillStyle='#f3f3ec';c.fillRect(0,0,view.w,view.h);c.save();c.beginPath();c.rect(view.x,view.y,W*s,H*s);c.clip();c.fillStyle='#fffef9';c.fillRect(view.x,view.y,W*s,H*s);for(let i=0;i<game.tiles.length;i++){const t=game.tiles[i],x=view.x+t.x*s,y=view.y+t.y*s;const known=t.explored||t.owner===1,visible=t.visible||t.owner===1;let fill;if(!known)fill='#f1f2eb';else if(t.blocked)fill='#e2e4db';else if(t.owner===1)fill=t.connected?'#abe5da':'#dfede1';else if(t.owner===2)fill='#f3c1ad';else fill='#fffef9';c.fillStyle=fill;c.fillRect(x,y,s+.3,s+.3);if(t.owner&&!t.connected&&known&&((t.x+t.y)%3===0)){c.strokeStyle=t.owner===1?'#a7c9ba':'#d3b7a4';c.lineWidth=.5;c.beginPath();c.moveTo(x,y+s);c.lineTo(x+s,y);c.stroke()}if(t.blocked&&known){c.fillStyle='#c5cfc5';roundRect(c,x+s*.17,y+s*.18,s*.67,s*.58,s*.15);c.fill()}if(t.source&&known){c.fillStyle='#c4a457';c.beginPath();const r=s*.31;c.arc(x+s/2,y+s/2,r,0,Math.PI*2);c.fill();c.strokeStyle='#fffdf6';c.lineWidth=1;c.stroke();if(!game.buildings.some(b=>b.x===t.x&&b.y===t.y&&b.hp>0)){c.strokeStyle='#c4a45770';c.beginPath();c.arc(x+s/2,y+s/2,s*(.63+Math.sin(time*2)*.08),0,Math.PI*2);c.stroke()}}if(!visible&&known&&t.owner!==1){c.fillStyle='#e3e6dc55';c.fillRect(x,y,s+.2,s+.2)}}
// Soft map coordinates give the white canvas a sense of scale without a rigid grid.
c.fillStyle='#526a5b15';for(let y=0;y<H;y+=4)for(let x=0;x<W;x+=4){c.beginPath();c.arc(view.x+x*s,view.y+y*s,.65,0,Math.PI*2);c.fill()}
for(const b of game.buildings){if(b.hp<=0)continue;const t=tileAt(b.x,b.y);if(b.team!==1&&!t?.visible)continue;drawBuilding(c,b,s,time)}
for(const u of game.units){if(u.hp<=0)continue;const t=tileAt(u.x,u.y);if(u.team!==1&&!t?.visible)continue;const x=view.x+u.x*s,y=view.y+u.y*s,r=Math.max(2.5,s*(u.type==='scout'?.27:.35));if(selection.includes(u.id)){c.strokeStyle=C.cyan;c.lineWidth=1;c.beginPath();c.arc(x,y,r+3,0,Math.PI*2);c.stroke()}c.fillStyle='#2849571a';c.beginPath();c.ellipse(x,y+2,r+1,r*.65,0,0,Math.PI*2);c.fill();c.fillStyle=color(u.team);c.strokeStyle='#fffdf8';c.lineWidth=Math.max(.8,s*.08);c.beginPath();if(u.type==='fighter'){c.rect(x-r,y-r,r*2,r*2)}else if(u.type==='breaker'){c.moveTo(x,y-r*1.25);c.lineTo(x+r,y+r);c.lineTo(x-r,y+r);c.closePath()}else c.arc(x,y,r,0,Math.PI*2);c.fill();c.stroke();if(u.hp<u.maxHp)healthbar(x,y+r+3,r*3,u.hp/u.maxHp,color(u.team))}
// Transient combat effects use simulation time so pausing freezes feedback.
for(const ev of game.events||[]){const age=game.time-ev.time;if(age<0||age>.7)continue;const origin=tileAt(ev.x,ev.y);if(!origin?.visible)continue;const alpha=1-age/.7;if(ev.type==='shot'&&ev.target){const targetTile=tileAt(ev.target.x,ev.target.y);if(!targetTile?.visible)continue;const ax=view.x+ev.x*s,ay=view.y+ev.y*s,bx=view.x+ev.target.x*s,by=view.y+ev.target.y*s;c.save();c.globalAlpha=alpha;c.strokeStyle=color(ev.team);c.lineWidth=Math.max(1,s*.1);c.beginPath();c.moveTo(ax,ay);c.lineTo(bx,by);c.stroke();c.fillStyle='#fffdf4';c.beginPath();c.arc(bx,by,s*.28*alpha+1,0,Math.PI*2);c.fill();c.strokeStyle=color(ev.team);for(let k=0;k<4;k++){const a=k*Math.PI/2+age*3,r=s*(.3+age);c.beginPath();c.moveTo(bx+Math.cos(a)*r,by+Math.sin(a)*r);c.lineTo(bx+Math.cos(a)*(r+2),by+Math.sin(a)*(r+2));c.stroke()}c.restore()}else if(ev.type==='build'){c.save();c.globalAlpha=alpha;c.strokeStyle=color(ev.team);c.lineWidth=1.5;c.beginPath();c.arc(view.x+(ev.x+.5)*s,view.y+(ev.y+.5)*s,s*(.7+age*3),0,Math.PI*2);c.stroke();c.restore()}}
if(hover&&mode){const x=Math.floor(hover.x),y=Math.floor(hover.y),t=tileAt(x,y);if(t){c.fillStyle=mode.kind==='build'?(t.owner===1&&t.connected&&!t.blocked?'#0aab7c25':'#e9685925'):'#20bfc133';c.strokeStyle=t.owner===1?C.cyan:C.coral;c.lineWidth=1;c.beginPath();c.arc(view.x+(x+.5)*s,view.y+(y+.5)*s,s*(mode.kind==='build'?3.5:4),0,Math.PI*2);c.fill();c.stroke();if(mode.kind==='build')drawBuilding(c,{x,y,team:1,type:mode.type},s,time,true)}}
if(drag&&!drag.touch&&Math.hypot(drag.last.x-drag.start.x,drag.last.y-drag.start.y)>9&&!mode){c.fillStyle='#13adb215';c.strokeStyle=C.cyan;c.fillRect(drag.start.x,drag.start.y,drag.last.x-drag.start.x,drag.last.y-drag.start.y);c.strokeRect(drag.start.x,drag.start.y,drag.last.x-drag.start.x,drag.last.y-drag.start.y)}if(moveMarker){moveMarker.life-=dt;c.strokeStyle=`rgba(19,173,178,${Math.max(0,moveMarker.life)})`;c.lineWidth=2;c.beginPath();c.arc(view.x+moveMarker.x*s,view.y+moveMarker.y*s,s*(1.5-moveMarker.life),0,Math.PI*2);c.stroke();if(moveMarker.life<=0)moveMarker=null}c.restore()}
function updateHUD(){const money=Math.floor(game.money[1]);$('money').textContent=money;const p=game.scores[1],a=game.scores[2];const percent=v=>v<=1?v*100:v;$('playerScore').textContent=percent(p).toFixed(1)+' %';$('enemyScore').textContent=percent(a).toFixed(1)+' %';$('playerBar').style.width=percent(p)+'%';$('enemyBar').style.width=percent(a)+'%';const t=Math.floor(game.time);$('clock').textContent=String(Math.floor(t/60)).padStart(2,'0')+':'+String(t%60).padStart(2,'0');selection=selection.filter(id=>game.units.some(u=>u.id===id&&u.hp>0));$('selectionTitle').textContent=selection.length?selection.length+' unité'+(selection.length>1?'s':'')+' sélectionnée'+(selection.length>1?'s':''):'Le cœur du réseau';$('selectionSub').textContent=selection.length?'Touchez le terrain pour donner un ordre.':'Étendez. Reliez. Conquérez.';document.querySelectorAll('[data-power]').forEach(b=>{const cd=Math.ceil(game.cooldowns?.[1]?.[b.dataset.power]||0);b.querySelector('small').textContent=cd>0?'Disponible dans '+cd+' s':b.dataset.power==='impulse'?'Portée +2 · 12 secondes':'Fragiliser une frontière';b.style.opacity=cd>0?'.55':'1'});const held=Math.max(game.hold?.[1]||0,game.hold?.[2]||0);$('objective').textContent=held>0?((game.hold[1]||0)>0?'VOUS':'IA')+' · VICTOIRE DANS '+Math.ceil(45-held)+' S':'OBJECTIF : 60 % PENDANT 45 S';document.querySelectorAll('[data-build],[data-recruit]').forEach(b=>b.classList.toggle('unaffordable',money<cost(b.dataset.build||b.dataset.recruit)));if(game.winner!==null&&game.winner!==undefined&&!ended){ended=true;audio(game.winner===1?'jingles_PIZZI03':'error_001');modal(`<div class="win-symbol">${game.winner===1?'◈':'◌'}</div><div class="eyebrow">LA TOILE A CHOISI SA COULEUR</div><h2>${game.winner===0?'Deux couleurs, une toile partagée.':game.winner===1?'Le monde vous appartient.':'Une couleur peut en cacher une autre.'}</h2><p>${game.winner===0?'Égalité : aucun camp n’a pris l’avantage au terme de la partie.':game.winner===1?'Votre réseau a tenu bon. Vos connexions ont fait la différence.':'Votre adversaire a pris le dessus. Essayez une expansion plus compacte et protégez vos relais.'}</p><div class="stat-row"><span>Votre territoire</span><strong>${percent(p).toFixed(1)} %</strong></div><div class="stat-row"><span>Durée</span><strong>${$('clock').textContent}</strong></div><button class="primary" id="again">Une nouvelle toile →</button><button id="endMenu" class="secondary">Retour au menu</button>`);$('again').onclick=start;$('endMenu').onclick=()=>{closeModal();playing=false;$('game').classList.add('hidden');$('menu').classList.remove('hidden');resize()}}}
function menuBackground(t){const c=bctx,w=bg.clientWidth,h=bg.clientHeight;c.clearRect(0,0,w,h);c.fillStyle='#f5f4ef';c.fillRect(0,0,w,h);const mobile=w<760,unit=mobile?13:22,ox=mobile?w*.62:w*.61,oy=h*.43;c.save();c.globalAlpha=mobile?.15:1;for(let y=-18;y<26;y++)for(let x=-15;x<30;x++){const dx=x*.93+Math.sin(y*.5)*1.7,dy=y;const d=Math.hypot(dx,dy*.82),e=Math.hypot(x-12,(y-10)*1.05);let col=null;if(d<11+Math.sin(x*.67+y*.48)*1.6)col=d<7?'#a8e2d6':'#d1ebe0';if(e<10+Math.sin(x*.55-y*.7)*1.5)col=e<6?'#f0b99f':'#eddbca';if(col){c.fillStyle=col;c.fillRect(ox+x*unit,oy+y*unit,unit+.5,unit+.5)}}c.strokeStyle='#fff8';c.lineWidth=2;c.setLineDash([2,5]);c.beginPath();c.moveTo(ox+unit*.5,oy+unit*.5);c.lineTo(ox-4*unit,oy+5*unit);c.lineTo(ox+unit,oy+8*unit);c.stroke();c.setLineDash([]);for(const [x,y,enemy,type]of [[0,0,false,'core'],[-4,5,false,'relay'],[1,8,false,'relay'],[10,13,true,'core'],[14,8,true,'relay']]){const px=ox+x*unit,py=oy+y*unit,r=type==='core'?18:11;c.fillStyle='#fffef6';c.strokeStyle=enemy?C.coral:C.cyan;c.lineWidth=3;c.shadowColor='#28495718';c.shadowBlur=15;c.shadowOffsetY=4;c.beginPath();for(let i=0;i<6;i++)c.lineTo(px+Math.cos(i*Math.PI/3)*r,py+Math.sin(i*Math.PI/3)*r);c.closePath();c.fill();c.stroke();c.shadowBlur=0;c.shadowOffsetY=0;c.fillStyle=c.strokeStyle;c.beginPath();c.arc(px,py,type==='core'?6:3,0,Math.PI*2);c.fill();if(type==='core'){c.strokeStyle=(enemy?C.coral:C.cyan)+'35';c.lineWidth=1;c.beginPath();c.arc(px,py,32+Math.sin(t)*3,0,Math.PI*2);c.stroke()}}for(let i=0;i<13;i++){const x=ox+(Math.sin(i*5.1)*4+Math.sin(t*.1+i)*.2)*unit,y=oy+(3+Math.cos(i*3.7)*5)*unit;c.fillStyle=C.cyan;c.strokeStyle='#fff';c.lineWidth=1;c.beginPath();c.arc(x,y,3.4,0,Math.PI*2);c.fill();c.stroke()}c.restore();if(!mobile){const grad=c.createLinearGradient(w*.29,0,w*.6,0);grad.addColorStop(0,'#f5f4ef');grad.addColorStop(1,'#f5f4ef00');c.fillStyle=grad;c.fillRect(0,0,w*.6,h)}}
function frame(now){const dt=Math.min((now-last)/1000||0,.05);last=now;menuTime=now/1000;if(playing&&game){if(!paused&&!ended)game.update(dt);drawMap(paused?0:dt,menuTime);updateHUD()}else menuBackground(menuTime);requestAnimationFrame(frame)}
// Mobile command tabs keep the map central and the touch targets generous.
const tabs=document.createElement('div');tabs.className='mobile-tabs';tabs.innerHTML='<button class="chosen" data-tab="build">◈ Développer</button><button data-tab="units">● Mobiliser</button><button data-tab="powers">✳ Pouvoirs</button>';$('game').querySelector('.command-panel').prepend(tabs);document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelector('.command-panel').dataset.tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(e=>e.classList.toggle('chosen',e===b));audio()});document.querySelector('.command-panel').dataset.tab='build';$('selectAll').innerHTML='▧ Toute l’armée';$('moveOrder').innerHTML='↗ Donner un ordre';resize();requestAnimationFrame(frame);

document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing&&!paused&&!ended)togglePause()});
